spec: "0.0"
name: google-assistant-demo
uuid: 51a14803-c8b3-4501-88d2-0198b7d75b8f
type: docker
onboot: []
services:
- name: google-assistant-demo
  uuid: 399abbe3-e30a-4190-8fd3-8b40fa2a5974
  image: ""
  directory: "./"
  net: "host"
  readonly: false
  forking: true
  command: ['python','-u','/opt/start.py']
  binds: ['/sys:/sys','/var/run/dbus:/var/run/dbus','/var/lib/connman:/var/lib/connman','/var/lib/alsa:/var/lib/alsa','/data/.config:/opt/.config --privileged']
  capabilities: [SYS_RAWIO,NET_ADMIN,SYS_TIME]
  devices: [/dev/mem,/dev/snd]
